### ISSUE TITLE
Code Structure can be improved

### ISSUE THREAD

**Issue by geekyharsh05** [nikita2060/100-days-of-python#1]
https://github.com/nikita2060/100-days-of-python/blob/3a4edd0d2f42a2a82996c99f5327e867317ca58a/Day15_coffee_machine.py#L57-L65

In the `sufficient_resource` function, the `else` statement should be outside the `for` loop. Otherwise, the function will return `True` as soon as it finds the first ingredient with sufficient resources, without checking the rest. 

Please fix the above mentioned lines else please assign me.

**Comment by nikita2060** [comment]
You are right. Thanks for pointing out
